package me.rosuh.easywatermark.ui
import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF6E5E00)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFE258)
val md_theme_light_onPrimaryContainer = Color(0xFF211B00)
val md_theme_light_secondary = Color(0xFF665E40)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFEEE2BC)
val md_theme_light_onSecondaryContainer = Color(0xFF211B04)
val md_theme_light_tertiary = Color(0xFF43664F)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFC5ECCE)
val md_theme_light_onTertiaryContainer = Color(0xFF002110)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF1D1B16)
val md_theme_light_outline = Color(0xFF7C7767)
val md_theme_light_inverseOnSurface = Color(0xFFF6F0E7)
val md_theme_light_inverseSurface = Color(0xFF32302A)
val md_theme_light_inversePrimary = Color(0xFFE5C50E)
val md_theme_light_surfaceTint = Color(0xFF6E5E00)
val md_theme_light_outlineVariant = Color(0xFFCDC6B4)
val md_theme_light_scrim = Color(0xFF000000)
val md_theme_light_surface = Color(0xFFFFF9EF)
val md_theme_light_onSurface = Color(0xFF1D1B16)
val md_theme_light_surfaceVariant = Color(0xFFE9E2D0)
val md_theme_light_onSurfaceVariant = Color(0xFF4B4739)

val md_theme_dark_primary = Color(0xFFE5C50E)
val md_theme_dark_onPrimary = Color(0xFF393000)
val md_theme_dark_primaryContainer = Color(0xFF534600)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFE258)
val md_theme_dark_secondary = Color(0xFFD1C6A1)
val md_theme_dark_onSecondary = Color(0xFF363016)
val md_theme_dark_secondaryContainer = Color(0xFF4D472A)
val md_theme_dark_onSecondaryContainer = Color(0xFFEEE2BC)
val md_theme_dark_tertiary = Color(0xFFA9D0B3)
val md_theme_dark_onTertiary = Color(0xFF143723)
val md_theme_dark_tertiaryContainer = Color(0xFF2B4E38)
val md_theme_dark_onTertiaryContainer = Color(0xFFC5ECCE)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1D1B16)
val md_theme_dark_onBackground = Color(0xFFE7E2D9)
val md_theme_dark_outline = Color(0xFF969080)
val md_theme_dark_inverseOnSurface = Color(0xFF1D1B16)
val md_theme_dark_inverseSurface = Color(0xFFE7E2D9)
val md_theme_dark_inversePrimary = Color(0xFF6E5E00)
val md_theme_dark_surfaceTint = Color(0xFFE5C50E)
val md_theme_dark_outlineVariant = Color(0xFF4B4739)
val md_theme_dark_scrim = Color(0xFF000000)
val md_theme_dark_surface = Color(0xFF15130E)
val md_theme_dark_onSurface = Color(0xFFCBC6BD)
val md_theme_dark_surfaceVariant = Color(0xFF4B4739)
val md_theme_dark_onSurfaceVariant = Color(0xFFCDC6B4)


val seed = Color(0xFFFFDE32)
val CustomColor1 = Color(0xFFD532E0)
val light_CustomColor1 = Color(0xFFA600B1)
val light_onCustomColor1 = Color(0xFFFFFFFF)
val light_CustomColor1Container = Color(0xFFFFD6F9)
val light_onCustomColor1Container = Color(0xFF37003B)
val dark_CustomColor1 = Color(0xFFFFA9FC)
val dark_onCustomColor1 = Color(0xFF590060)
val dark_CustomColor1Container = Color(0xFF7E0088)
val dark_onCustomColor1Container = Color(0xFFFFD6F9)

