name: Publish Release to Play Store

env:
  GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx3072m -Dfile.encoding=UTF-8 -XX:+HeapDumpOnOutOfMemoryError -XX:MaxMetaspaceSize=1g" -Dkotlin.daemon.jvm.options="-Xmx2560m" -Dkotlin.incremental=false
  CI_GRADLE_ARG_PROPERTIES: --stacktrace -PpreDexEnable=false --max-workers 2 --no-daemon

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - id: fetchLatestRelease
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: ${{ github.repository }}
          excludes: prerelease, draft
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Print Latest Release
        run: echo ${{ steps.fetchLatestRelease.outputs.release }}
      - name: Prepare Release Artifact
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          file: 'app-release.aab'
      - name: Prepare Release mapping
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          file: 'mapping.txt'
      - name: List files
        run: ls -l
      - name: Upload Android Release to Play Store
        uses: r0adkll/upload-google-play@v1.1.3
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: me.rosuh.easywatermark
          releaseFiles: 'app-release.aab'
          track: production
          mappingFile: 'mapping.txt'
