name: Generated APK AAB (Upload - Create Artifact To Github Action)

env:
  # The name of the main module repository
  main_project_module: app

on:
#  release:
#    types: [published]
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - id: fetchLatestRelease
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: ${{ github.repository }}
          excludes: prerelease, draft
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Prepare Release Artifact
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'dsaltares/godot-wild-jam-18'
          version: ${{ steps.fetchLatestRelease.fetchLatestRelease.release }}
          file: '*.aab'
          token: ${{ secrets.GITHUB_TOKEN }}
#      - name: Upload Android Release to Play Store
#        uses: r0adkll/upload-google-play@v1.1.3
#        with:
#          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
#          packageName: me.rosuh.easywatermark
#          releaseFiles: '*.aab'
#          track: production
#          status: inProgress
#          mappingFile: app/build/outputs/mapping/release/mapping.txt
